name       : kmahjongg
version    : 22.08.3
release    : 43
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kmahjongg-22.08.3.tar.xz : 24360d1ed40c77257780578fc09c45dc74191c7d449dcfb89920b2e8a1dcbc9c
homepage   : https://kde.org/applications/games/org.kde.kmahjongg
license    : GPL-2.0-or-later
component  : games.puzzle
summary    : Plasma's version of the famous Mahjongg solitaire game
description: |
    Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
    This game is part of the Plasma desktop environment.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - knewstuff-devel
    - libkdegames-devel
    - libkmahjongg-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
