name       : kmahjongg
version    : 21.12.3
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/kmahjongg-21.12.3.tar.xz : 3d7cdbced612c82b86ebf3824e331002cda7b283bdec5f0891eb9539f9dddb0b
homepage   : https://kde.org/applications/games/org.kde.kmahjongg
license    : GPL-2.0-or-later
component  : games.puzzle
summary    : Plasma's version of the famous Mahjongg solitaire game
description: |
    Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
    This game is part of the Plasma desktop environment.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - knewstuff-devel
    - libkdegames-devel
    - libkmahjongg-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
