name       : kmahjongg
version    : 23.04.2
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/kmahjongg-23.04.2.tar.xz : 28871d3b5260f33afa630397fd5a60b9d3c33b0a54545a15576b1372b129b1cc
homepage   : https://kde.org/applications/games/org.kde.kmahjongg
license    : GPL-2.0-or-later
component  : games.puzzle
summary    : Plasma's version of the famous Mahjongg solitaire game
description: |
    Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
    This game is part of the Plasma desktop environment.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - knewstuff-devel
    - libkdegames-devel
    - libkmahjongg-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
