name       : kmahjongg
version    : 19.04.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.3/src/kmahjongg-19.04.3.tar.xz : 41bd533bf8d8b1e04451cb3c9165b08f9135603c0085d8b402d0e8e026b8ed00
license    : GPL-2.0-or-later
component  : games.puzzle
summary    : Plasma's version of the famous Mahjongg solitaire game
description: |
    Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
    This game is part of the Plasma desktop environment.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - knewstuff-devel
    - libkdegames-devel
    - libkmahjongg-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
