name       : kmahjongg
version    : 20.12.2
release    : 26
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kmahjongg-20.12.2.tar.xz : ccb747622e80a4a82685af89cb4e2eff93b3961e9c1a8bc3514646b7278cb614
homepage   : https://kde.org/applications/games/org.kde.kmahjongg
license    : GPL-2.0-or-later
component  : games.puzzle
summary    : Plasma's version of the famous Mahjongg solitaire game
description: |
    Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
    This game is part of the Plasma desktop environment.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - knewstuff-devel
    - libkdegames-devel
    - libkmahjongg-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
