name       : kmahjongg
version    : 20.04.2
release    : 17
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/kmahjongg-20.04.2.tar.xz : 14981f2403c029365fa965cdf29f4608dd8d124871be409cb2eed340b47b0de9
homepage   : https://kde.org/applications/games/org.kde.kmahjongg
license    : GPL-2.0-or-later
component  : games.puzzle
summary    : Plasma's version of the famous Mahjongg solitaire game
description: |
    Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
    This game is part of the Plasma desktop environment.
builddeps  :
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - knewstuff-devel
    - libkdegames-devel
    - libkmahjongg-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |-
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
